[phases.setup]
nixpkgsArchive = "1267bb4920d0fc06ea916734c11b0bf004bbe17e"
nixPkgs = ["nodejs_24", "openssl"]
aptPkgs = []

[phases.install]
cmds = [
    "npm install -g corepack@latest",
    "corepack enable",
    "corepack install -g pnpm@10.33.2",
    "pnpm install --frozen-lockfile",
]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "node .output/server/index.mjs"
